subsetData <- read.csv("subsetData.csv",stringsAsFactors = FALSE)
str(subsetData)
png(file="plot1.png",width = 480, height = 480)
hist(as.numeric(subsetData$Global_active_power),breaks=11,col="red",main="Global Active Power", xlab="Global Active Power(kilowatts")
dev.off()
