subsetData <- read.csv("subsetData.csv",stringsAsFactors = FALSE)
str(subsetData)
png(file = "plot2.png",width = 480, height = 480)
plot(as.numeric(subsetData$Global_active_power),main="Global Active Power",type="l", ylab="Global Active Power(kilowatts)",xlab="",axes=FALSE)
axis(1, at = c(0,1500,2900),labels = c("Thu","Fri","Sat"))
axis(2,at=c(0,2,4,6))
box(lty = 1, col = 'black')
dev.off()
